import Link from "next/link";
import Icon from "@/components/Icon";
import FAQ from "@/components/FAQ";

export const metadata={title:"About Gara Music — Music discovery with intent",description:"Learn how the Gara Music platform is structured."};

export default function AboutPage(){return <main>
 <section className="inner-hero"><div className="mx-auto max-w-7xl px-5 py-20 sm:px-8 lg:py-28"><p className="section-kicker">About Gara Music</p><h1 className="inner-title">A music product with<br/><em>room to grow.</em></h1><p className="inner-lead">Gara Music is being shaped as a serious music discovery and listening experience: deep enough to explore, simple enough to return to.</p></div></section>
 <section className="mx-auto max-w-7xl px-5 py-20 sm:px-8 lg:py-28" id="platform"><div className="about-grid"><div><p className="section-kicker">Product philosophy</p><h2 className="section-title-lg">Less interface.<br/><em>More intention.</em></h2></div><div className="about-copy"><p>Music platforms can become crowded with controls, promotions and competing surfaces. Gara Music takes a more deliberate approach: discovery is prominent, playback persists, and the catalogue remains the centre of the experience.</p><p>As the product grows, the same system can support richer artist pages, editorial collections, creator workflows and verified business information.</p></div></div>
  <div className="about-principles"><div><Icon name="compass" size={22}/><h3>Discovery first</h3><p>Search, genres, trending music and related listening are connected.</p></div><div><Icon name="shield" size={22}/><h3>Trust by default</h3><p>Business claims, reviews and contact details should be verified before publication.</p></div><div><Icon name="globe" size={22}/><h3>Built to expand</h3><p>The information architecture leaves room for new catalogues and business services.</p></div></div>
 </section>
 <section className="business-band"><div className="mx-auto max-w-7xl px-5 py-20 sm:px-8 lg:py-28"><div className="business-band-grid"><div><p className="section-kicker">What comes next</p><h2 className="section-title-lg">A bigger platform,<br/><em>without the bloat.</em></h2></div><div className="roadmap-list"><div><b>01</b><span>Creator profiles & richer release pages</span></div><div><b>02</b><span>Editorial playlists and collections</span></div><div><b>03</b><span>Verified business contact and conversion flows</span></div><div><b>04</b><span>More catalogue sources as integrations mature</span></div></div></div></div></section>
 <section className="mx-auto max-w-4xl px-5 py-20 sm:px-8 lg:py-28"><p className="section-kicker">FAQ</p><h2 className="section-title-lg mt-2">Common questions.</h2><div className="mt-8"><FAQ/></div><div className="mt-10 flex flex-wrap gap-3"><Link href="/search" className="button-secondary">Explore music <Icon name="arrow" size={15}/></Link><Link href="/contact" className="button-ghost">Contact <Icon name="arrow" size={15}/></Link></div></section>
 </main>}
