import Link from "next/link";
import Icon from "@/components/Icon";
export const runtime = 'edge';
export const metadata={title:"Gara Music — Plans",description:"Gara Music product and service plans."};
const plans=[
 {name:"Listener",price:"Free",desc:"For people who want a focused way to discover and save music.",items:["Catalogue discovery","Search & genre browsing","Persistent player","Personal library"],cta:"Start exploring"},
 {name:"Creator",price:"Custom",desc:"For artists and music teams that need a richer product surface.",items:["Creator-ready profiles","Release presentation","Discovery surfaces","Business onboarding"],cta:"Discuss a use case",featured:true},
 {name:"Platform",price:"Custom",desc:"For organizations that need a music experience around their own workflow.",items:["Custom product scope","Integration planning","Business contact flow","Launch support"],cta:"Talk to Gara Music"}
];
export default function PricingPage(){return <main><section className="inner-hero"><div className="mx-auto max-w-7xl px-5 py-20 sm:px-8 lg:py-28"><p className="section-kicker">Plans & services</p><h1 className="inner-title">Simple paths.<br/><em>Serious products.</em></h1><p className="inner-lead">Pricing should reflect the actual service being delivered. Listener access can stay open, while creator and platform work can be scoped to the business.</p></div></section><section className="mx-auto max-w-7xl px-5 pb-24 sm:px-8"><div className="pricing-grid">{plans.map(p=><article className={`price-card ${p.featured?"featured":""}`} key={p.name}>{p.featured&&<span className="price-badge">BUSINESS</span>}<div className="price-icon"><Icon name={p.name==="Listener"?"headphones":p.name==="Creator"?"music":"globe"} size={19}/></div><h2>{p.name}</h2><p>{p.desc}</p><div className="price-value">{p.price}</div><ul>{p.items.map(i=><li key={i}><Icon name="check" size={15}/>{i}</li>)}</ul><Link href={p.name==="Listener"?"/search":"/contact"} className="price-cta">{p.cta}<Icon name="arrow" size={14}/></Link></article>)}</div><p className="mx-auto mt-8 max-w-2xl text-center text-[11px] leading-6 text-[#676070]">Business pricing, contact details and any commercial claims should be replaced with the verified information for the operating business before launch.</p></section></main>}
